fix warning in drivers/video/aty/atyfb_base.c, #2
fix this warning:

  drivers/video/aty/atyfb_base.c:532: error: ‘ram_dram' defined but not used
  drivers/video/aty/atyfb_base.c:533: error: ‘ram_resv' defined but not used

ram_dram is used in the CONFIG_FB_ATY_GX case only,
ram_resv is used when either CONFIG_FB_ATY_GX or CONFIG_FB_ATY_CT is enabled.

Signed-off-by: Ingo Molnar <mingo@elte.hu>