werror: depends on !ENABLE_WARN_DEPRECATED && !ENABLE_MUST_CHECK
There's way too many deprecated-API and must-check-API-use warnings,
so do not generate these when CONFIG_ALLOW_WARNINGS is disabled.

Signed-off-by: Ingo Molnar <mingo@elte.hu>